apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-pod-test
spec:
  replicas: 2                 # <- creates two Pods
  selector:
    matchLabels:
      app: two-pod-test
  template:
    metadata:
      labels:
        app: two-pod-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        readinessProbe:        # quick, lightweight probe
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: two-pod-test-svc
spec:
  selector:
    app: two-pod-test
  ports:
  - port: 80          # service port inside the cluster
    targetPort: 80    # containerPort
  type: ClusterIP     # change to NodePort/LoadBalancer if you need external access

